### ISSUE TITLE
Document lib-node

### ISSUE THREAD

**Issue by jsi** [enonic/doc-xp#10]

**Comment by ComLock** [comment]
@jsi Does this include repoconnection? Or should there be a separate task for that?

Exists
https://repo.enonic.com/public/com/enonic/xp/docs/7.0.0-RC1/docs-7.0.0-RC1-libdoc.zip!/module-node-RepoConnection.html

Removed
https://repo.enonic.com/public/com/enonic/xp/docs/7.0.0/docs-7.0.0-libdoc.zip!/module-node-RepoConnection.html

**Comment by GlennRicaud** [comment]
Already fixed there: https://github.com/enonic/xp/issues/7116
Might have to rebuild v7.0.0 with this fix though
