### ISSUE TITLE
Content types page is incomplete

### ISSUE THREAD

**Issue by alansemenov** [enonic/doc-xp#106]
[This page ](https://developer.enonic.com/docs/xp/stable/cms/content-types) is missing lots of descriptions of built-in content types and properties which were documented in [the old docs](https://xp.readthedocs.io/en/stable/developer/site/content-types/index.html)

**Comment by poi33** [comment]
@hjelmevold is this completed now or does it still need more work?

**Comment by poi33** [comment]
https://github.com/enonic/doc-xp/pull/116
