### ISSUE TITLE
Deployment .cfg

### ISSUE THREAD

**Issue by poi33** [enonic/doc-xp#110]
The deployment config file was never documented. 
com.enonic.xp.server.deploy.cfg

Please add this to the documentation.

**Comment by rymsha** [comment]
So for now it is better to stay undocumented.

`interval = 1000` - scan interval in milliseconds. Nobody wants to modify this. Make it smaller and waste CPU. Make it larger - and XP won't deploy applications as snappy as it could.

Deploy applications from their URLs? This is really asking for troubles in cluster deployments enonic/xp#7837. Stay away from this config in production.

**Comment by poi33** [comment]
Ok, so this is not needed. Will close this 👍
