### ISSUE TITLE
Document Development mode

### ISSUE THREAD

**Issue by rymsha** [enonic/doc-xp#148]
In a few places documentation mentions XP development mode. For instance https://developer.enonic.com/docs/enonic-cli/master#deploy

But Development mode is not explained:
- What is it for?
- When (not) to use  it?
- What does it do?

**Comment by thomasheartman** [comment]
Does this concern the XP docs or the CLI docs? Both? #247 is similar to this, but only concerns the XP docs. It's also more about the difference between dev mode and continuous builds. 

If this is about the XP docs, are the changes introduced in #248  sufficient?

**Comment by rymsha** [comment]
- What is it for?
I think it is covered

- When (not) to use it?
Big red warning should exist in docs, that development mode is not for production. It is not only a performance concern, but also a security concern.

- What does it do?
I think, there is a mistake in your latest changes. Development mode does not redeploy apps.
Instead it 
- disables some cache mechanisms in XP
- reads resources from directly from source locations

**Comment by thomasheartman** [comment]
Got it! Thanks for the feedback and for clearing up how dev mode works! I'll go and make sure to correct it and add the warning about production use 👍🏾

**Comment by alansemenov** [comment]
Will be fixed in https://github.com/enonic/doc-xp/issues/247
