### ISSUE TITLE
document multirepoconnect.query with sources set to an empty array queries ALL REPOS

### ISSUE THREAD

**Issue by ComLock** [enonic/doc-xp#160]
If this is true seems like a major security issue to me. I discovered it while working on https://github.com/enonic/app-explorer/issues/91 when querying an Explorer interface without any collections (repos) selected.

doc: https://developer.enonic.com/docs/xp/stable/api/lib-node#multirepoconnect

**Comment by rymsha** [comment]
Functionality won't change as it is likely to be desired one - how to specify to search in all repositories.

**Comment by alansemenov** [comment]
@sigdestad Should we allow empty array in `sources` as a way to connect to all available repos or is this a bug?

**Comment by sigdestad** [comment]
Sounds natural to me, what other options do we have? Also, changing this would effectively break API I guess?
