### ISSUE TITLE
Document `com.enonic.xp.extractor.cfg`

### ISSUE THREAD

**Issue by alansemenov** [enonic/doc-xp#167]
We haven't documented `body.size.limit` property and the new config file `com.enonic.xp.extractor.cfg` implemented in
https://github.com/enonic/xp/issues/7294. 

Should be [here](https://developer.enonic.com/docs/xp/stable/deployment/config#xp_config_files)

**Comment by rymsha** [comment]
Maybe it is a duplicate of #112 ? Or at least should be done together
