### ISSUE TITLE
Missing documentation for Roles in Enonic XP

### ISSUE THREAD

**Issue by mortyeriksen** [enonic/doc-xp#183]
There is some doc about the project-specific roles, but we are missing the general roles like content manager admin, content manager app, authenticated etc. It's mentioned in the text, but you can't search for the roles. We should have an overview?

This is what I answered SSB when they asked: "Har dere en greit oversikt over hvilke roller som er innebygd i Enonic XP, og hva de ulike rollene har av betydning?"

---
Takk for henvendelsen.

Følgende roller er innbygd:
* Administration Console Login - Tilgang til å logge inn i XP admin
* Administrator - Full tilgang til XP admin
* Content Manager App - Tilgang til Content Studio
* Content Manager Administrator - Full tilgang til Content Studio
* Authenticated - Innloggende brukere
* Everyone - Alle brukere

Dersom dere kjører siste versjon av Enonic XP, så har dere funksjonen for prosjekter. Når man oppretter et prosjekt, så kan man spesifisere roller som beskrevet her:
https://developer.enonic.com/docs/xp/stable/cms/projects

Utover disse baserollene oppretter man grupper og gir tilgang som beskrevet her:
https://developer.enonic.com/docs/content-studio/stable/permissions

Jeg håper det svarer på spørsmål. Jeg vil også anbefale deg å registrere deg på vår community (slack.enonic.com) for å få hjelp med generelle spørsmål. SSB har også support med SLA hvor saker legges inn her: https://support.enonic.com.

**Comment by alansemenov** [comment]
We also have these built-in roles in addition to the ones you mentioned:

Users App - Tilgang til bruker app'en
Users Administrator - Tilgang til bruker app'en + mulighet for bruker styring
Content Manager Expert - Har tilgang til kildekode i HTML Area og rettigheter i Content Studio

**Comment by alansemenov** [comment]
Here's overview in the old docs: https://xp.readthedocs.io/en/6.15/admin/users/roles.html

**Comment by alansemenov** [comment]
https://developer.enonic.com/docs/xp/stable/iam#built_in_roles
