### ISSUE TITLE
Write a guide on 'Introduction to NoSQL with Enonic XP'

### ISSUE THREAD

**Issue by poi33** [enonic/doc-xp#19]
The NoQL reference is written for exports, not for people wanting to use queries. 
Its only technical with little to no explination and it is hard to understand. 
It needs more examples and show how each of the different aspects of the language is used.

```
constraintExpr = compareExpr
               | logicalExpr
               | functionExpr
               | notExpr ;
```

Is impossible to understand what is going on unless you have indepth knowledge of each of the different terms. 

Suggestion: show a simple query a practical example and break it down into different parts.

```
propertyPath
Grammar

propertyPath = pathElement ( '.' pathElement )* ;
pathElement  = ( [ validJavaIdentifier - '.' ] )* ;

Examples

myProperty
data.myProperty
data.myCategory.myProperty
```
Example above from the documentation. 
This only shows how its used and some examples. 
No explination and the examples are not full queries, only a subset of an usable example.

**Comment by poi33** [comment]
This should be updated in the older xp-doc!. It would be a huge benefit for everyone using  XP 6 (or older) systems.

**Comment by sigdestad** [comment]
@poi33 - This is intentional as this is the _hardcore_ node API documentation. We will create guides that take you though performing basic tasks and with hands on examples..

BTW: Don't you know EBNF? :-)

**Comment by jsi** [comment]
This is covered by our courses and the class participants are complaining about the bad doc.  If the solution is to write a guide, I will change this issue into "Write a guide for 'Introduction to NoSQL with Enonic XP'" or something like that.

**Comment by poi33** [comment]
A guide is something i can point out to participants, but i cant use that when teaching. I don't feel comfortable teaching queries if they cant use the documentation to see how its used. So I'm still stuck with trying to explain a subject with documentation that is hard to understand.

**Comment by sigdestad** [comment]
This will be covered by misc guides. Closing issue
