### ISSUE TITLE
Write documentation for installing XP as a service in Windows

### ISSUE THREAD

**Issue by runarmyklebust** [enonic/doc-xp#20]
Ref this support-issue, where the customer asks for documentation on how to run xp as a service in windows: https://enonic.zendesk.com/agent/tickets/2907
They will be running xp7.

We have documentation on how to run XP6 as a linux-service: https://xp.readthedocs.io/en/latest/operations/linux-detail-service-install.html?highlight=service

I got some info from an existing customer running XP-cluster on windows:

>
> We are using «windows service wrapper»: https://github.com/kohsuke/winsw
> Use -Dhttps.proxyHost if you are behind a proxy to get e.g market.enonic.com to work

Here are some example files from their setup:

https://drive.google.com/drive/folders/1-fXu0QwwifNetKuGBqIezAfNhEpJOokw?usp=sharing

**Comment by sigdestad** [comment]
I'm thinking maybe we should place this in a guide? Let's have a discussion...

**Comment by runarmyklebust** [comment]
The customer is still waiting for this, so I think it should be prioritized now maybe?

**Comment by sigdestad** [comment]
This should _not_ be in the XP docs, so someone have to make this as a Guide
I propose we have the Minsk team take care of it?

**Comment by pmi** [comment]
Done in https://github.com/enonic/guide-xp-as-windows-service

**Comment by alansemenov** [comment]
https://developer.enonic.com/guides/run-xp-as-a-service
