### ISSUE TITLE
Enonic XP 7.0 - Lib upgrade

### ISSUE THREAD

**Issue by ComLock** [enonic/doc-xp#21]
I would like a 'Enonic XP 7.0 - Lib upgrade' doc
Similar to https://developer.enonic.com/docs/xp/stable/release/apps-upgrade

For example a lib does not use com.enonic.xp.app thus xp.enonicRepo() will fail.

Instead a lib should use com.enonic.xp.base as seen here:

https://github.com/enonic/starter-lib/blob/master/build.gradle#L4

**Comment by alansemenov** [comment]
[Added a section](https://developer.enonic.com/docs/xp/stable/release/apps-upgrade#library_upgrade) on lib upgrade
