### ISSUE TITLE
Scheduler library: timezone or timeZone?

### ISSUE THREAD

**Issue by ComLock** [enonic/doc-xp#314]
The doc is inconsistent https://developer.enonic.com/docs/xp/stable/api/lib-scheduler

Also for diffing purposes it would be nice if the output match the input...

Example:
https://github.com/enonic/lib-explorer/blob/master/src/main/resources/lib/explorer/scheduler/createOrModifyJob.es#L37

**Comment by ComLock** [comment]
I think the problem is only the doc. It should always be timeZone with a big Z.

My diff issue was "my bad":
Sent in: 'GMT+2:00'
Stored and returned as 'GMT+02:00'

**Comment by rymsha** [comment]
I can't find `timezone` on that page. only `timeZone`
