### ISSUE TITLE
Document Management endpoint

### ISSUE THREAD

**Issue by alansemenov** [enonic/doc-xp#32]
https://developer.enonic.com/docs/xp/stable/api/management

Endpoint is available at port 4848 (http://localhost:4848)

Add documentation on management endpoint used by CLI. Basically document how to execute each command [described here](https://xp.readthedocs.io/en/stable/reference/toolbox/index.html) by using REST endpoint.

**Comment by sigdestad** [comment]
This looks comprehensive now Pavel, is it done?
