### ISSUE TITLE
Hazelcast lite/light member

### ISSUE THREAD

**Issue by hjelmevold** [enonic/doc-xp#325]
Hazelcast themselves use "Lite member" terminology.
Unclear in the docs if the `lightMember` config param is correct, or if it should be `liteMember`, since there is an inconsistency with the parameter description in the docs.

Also, should we recommend master nodes to be lite member?

---
#### Document Details

⚠ *Please do not edit this section. It helps us track and organize our issues.*

* Commit: 1ca40bfa06bf33bc4bcca6eb768c80dcd0c9df7a
* Document: Configuration files
* Document path: /developer/docs/xp/stable/deployment/config

**Comment by rymsha** [comment]
in XP code it is `light`. But it is truly a typo. :( Hazelcast calls it `lite`.

lightMember (aka lite member) is to reduce heap usage on certain nodes. Sounds good for master nodes, but we didn't try it properly, and I'm leaning to call it an experimental feature instead.
if `isMaster` is used extensively in app, setting "lightMember = true" may hurt performance (or may not, depending on what it is used for)
"lightMember = true" also disallows certain Hazelcast collections (ReplicatedMap). we don't use it yet. But any recommendation would leave us with less flexibility.

**Comment by rymsha** [comment]
Starting from XP 7.9 configuration will be called `liteMember` 
`lightMember` will work for now, too. But will be removed at some point
