### ISSUE TITLE
lib-scheduler#create documentation doesn't explain format of task descriptor

### ISSUE THREAD

**Issue by ComLock** [enonic/doc-xp#326]
https://developer.enonic.com/docs/xp/stable/api/lib-scheduler#create

One can see what it looks like in the example code here:
https://developer.enonic.com/docs/xp/stable/api/lib-scheduler#get

But it is not explained what it is. Since it's something the developer has to pass as a parameter to create, it might be a good idea to explain what it is: `${app.name}:${taskName}`

**Comment by rymsha** [comment]
PR is wellcome

**Comment by rymsha** [comment]
it is well explained in https://developer.enonic.com/docs/xp/stable/framework/scheduler
