### ISSUE TITLE
fieldset is wrong

### ISSUE THREAD

**Issue by reinaldoams** [enonic/doc-xp#361]
it's `<fieldset>` when it should be `<field-set>`

---
#### Document Details

⚠ *Please do not edit this section. It helps us track and organize our issues.*

* Commit: 6d8ffe6c79d28dec64e97f10e830905655c97b05
* Document: Enonic XP 7.0 - Application upgrade
* Document path: /developer/docs/xp/stable/release/apps-upgrade

**Comment by alansemenov** [comment]
@reinaldoams You should point to the place in the docs where it's wrong. It's impossible to guess.

**Comment by reinaldoams** [comment]
It's in the "Document path" below my comment, but being more specific, it's here:
https://developer.enonic.com/docs/xp/stable/release/apps-upgrade#fieldset

**Comment by alansemenov** [comment]
Fixed, thanks for pointing out
