### ISSUE TITLE
Css link should have rel="stylesheet"

### ISSUE THREAD

**Issue by reinaldoams** [enonic/doc-xp#367]
In the example usage, when putting a css in pageContributions, there should be a `rel="stylesheet` there for it to work.
[Link to highlight here.](https://developer.enonic.com/docs/xp/stable/cms/macros#:~:text=pageContributions%3A%20%7B%0A%20%20%20%20%20%20%20%20%20%20%20%20headEnd%3A%20%5B%0A%20%20%20%20%20%20%20%20%20%20%20%20%20%20%20%20%27%3Clink%20href%3D%22%27%20%2B%20portalLib.assetUrl(%7Bpath%3A%20%27css/current%2Duser.css%27%7D)%20%2B%20%27%22/%3E%27%0A%20%20%20%20%20%20%20%20%20%20%20%20%5D%0A%20%20%20%20%20%20%20%20%7D%0A%20%20%20%20%7D)

---
#### Document Details

⚠ *Please do not edit this section. It helps us track and organize our issues.*

* Commit: 7463f6633e3cec747eae3bdad2b21a2f6bb6e3cd
* Document: Macros
* Document path: /developer/docs/xp/stable/cms/macros

**Comment by poi33** [comment]
Updated the docs now. 
Thanks for reporting this reinaldoams
