### ISSUE TITLE
Enonic XP DOC Deployment and hosting missing content

### ISSUE THREAD

**Issue by poi33** [enonic/doc-xp#38]
Still more work needs to be done on the "Deployment and hosting" in the doc:

https://developer.enonic.com/docs/xp/stable/deployment

**Comment by jsi** [comment]
A lot has been done in this section since this issue was written, including a new page on Docker, a section on XP_HOME and a page on Data Management.  Does this serve the needs you had, @poi33 , or is there anything else you are looking for?

**Comment by poi33** [comment]
I think we can close this now. 
The things i was looking for are spread around the docs, and if more work is done then we can just close this.
