### ISSUE TITLE
wrong css path

### ISSUE THREAD

**Issue by reinaldoams** [enonic/doc-xp#386]
Css path in the second example is wrong.
It's: /site/styles.css
It should be: resources/assets/styles/styles.css

https://developer.enonic.com/docs/xp/stable/cms/styles

---
#### Document Details

⚠ *Please do not edit this section. It helps us track and organize our issues.*

* Commit: 6552365f95e99e27d0caf5a7f62fe6e427e3c7ba
* Document: Custom styles
* Document path: /developer/docs/xp/stable/cms/styles

**Comment by alansemenov** [comment]
@felipestanzani Thank you for reporting, this should be fixed now.
