### ISSUE TITLE
Wrong xml ending tag used

### ISSUE THREAD

**Issue by anton-lilleby** [enonic/doc-xp#409]
```
<part>
  <display-name>Content List</display-name>
  <form />
</layout>
```
Should probably end with part?

---
#### Document Details

⚠ *Please do not edit this section. It helps us track and organize our issues.*

* Commit: aa9626e52f72b5df84aab313e0b24362902536c1
* Document: Components
* Document path: /developer/docs/xp/stable/cms/components

**Comment by alansemenov** [comment]
Thanks - fixed.
