### ISSUE TITLE
keys in repo.get should be key

### ISSUE THREAD

**Issue by reinaldoams** [enonic/doc-xp#451]
Hi.
When using this lib, I'm not able to use "keys" as a parameter. I get the error "Parameter 'key' is required".
I suggest that for this part of the documentation should change to having "key" as the parameter for this function.

---
#### Document Details

⚠ *Please do not edit this section. It helps us track and organize our issues.*

* Commit: a5511f5ae5ffc2a76b9ae69bbf010ca8a304d343
* Document: Node Library
* Document path: /developer/docs/xp/stable/api/lib-node

**Comment by alansemenov** [comment]
@reinaldoams Thanks for reporting the issue, should be correct now.
