### ISSUE TITLE
Logging in tests?

### ISSUE THREAD

**Issue by ComLock** [enonic/doc-xp#46]
I tried log.info in a test. The test runs, but where did the log go? To nowhere?

How can I inspect values in a test?

**Comment by rymsha** [comment]
Some say, logging in unit tests is a sin https://www.yegor256.com/2021/08/11/logging-in-unit-tests.html
I tend to agree and don't want to support this bad practice.

Have you tried to use assertXXX ?

**Comment by poi33** [comment]
Logging in it self is not a bad practice. 
If you log to visualy assert something that is super bad. 
If a test fails and we cant properly print it to console or show it in a meaningful way that is also super bad. 
This should be supported.

**Comment by rymsha** [comment]
> If a test fails and we cant properly print it to console or show it in a meaningful way that is also super bad.

This is what assertXXX methods should do.

**Comment by poi33** [comment]
Closing this as it seems its bas practice to log in tests
