### ISSUE TITLE
Nashorn is not used anymore

### ISSUE THREAD

**Issue by felipestanzani** [enonic/doc-xp#505]
You should change the documentation and remove Nashorn as scripting engine, since the javascript engine was changed in enonic 7.13.1.

---
#### Document Details

⚠ *Please do not edit this section. It helps us track and organize our issues.*

* Commit: bea5e7f2686f8388688fafe3675fd61bd8644285
* Document: Javascript Framework
* Document path: /developer/docs/xp/stable/framework

**Comment by alansemenov** [comment]
https://developer.enonic.com/docs/xp/stable/framework

**Comment by rymsha** [comment]
It is still Nashorn in 7.13.x
