### ISSUE TITLE
We need a list of event types in the doc.

### ISSUE THREAD

**Issue by jsi** [enonic/doc-xp#54]
Ref this feedback on Discuss: https://discuss.enonic.com/t/list-of-event-types/1589

**Comment by poi33** [comment]
This is probably solved by: 
https://developer.enonic.com/docs/xp/stable/api/lib-node#events
https://developer.enonic.com/docs/xp/stable/api/lib-repo#events
https://developer.enonic.com/docs/xp/stable/api/lib-task#events

Could be we are missing more, but that would be a seperate issue.
