### ISSUE TITLE
Document Image Service

### ISSUE THREAD

**Issue by jsi** [enonic/doc-xp#59]
https://developer.enonic.com/docs/xp/stable/runtime/image-service
https://developer.enonic.com/docs/xp/stable/runtime/media/image-service

**Comment by jsi** [comment]
Dokuementasjonen fra 6.15 kan ifølge TSI flyttes over uten endringer.

**Comment by sigdestad** [comment]
NB! Jeg tror ikke selve image service er dokumentert i 6.15, men portalfunksjoner. La oss se på denne sammen!
