### ISSUE TITLE
Cleanup TODOs: Complete Storage documentation

### ISSUE THREAD

**Issue by jsi** [enonic/doc-xp#60]
There are lots of TODOs in these pages:
https://developer.enonic.com/docs/xp/stable/storage
https://developer.enonic.com/docs/xp/stable/storage/system-properties
https://developer.enonic.com/docs/xp/stable/storage/indexing
https://developer.enonic.com/docs/xp/stable/storage/branches
https://developer.enonic.com/docs/xp/stable/storage/noql

**Comment by poi33** [comment]
While there is probablly more work to be done on the storage pages. 
It looks like it covers all areas now. Prefer if we open new issues if we find missing documentation.
