### ISSUE TITLE
Set up links to reference documentation for the Java bridge

### ISSUE THREAD

**Issue by jsi** [enonic/doc-xp#67]
https://developer.enonic.com/docs/xp/stable/framework/java-bridge

**Comment by jsi** [comment]
Hardcoded version checked in.  Need to find a solution that can replace {release} with the current version, to always get the latest doc.

**Comment by sigdestad** [comment]
We will not be updating the docs for 7.0.2 etc, so this is not a problem. Only major/feature releases should be listed

**Comment by sigdestad** [comment]
You should have conferred with me on this issue.
Now the doc says "Enonic XP 7.0.2 documentation", but this is not correct as the url to this doc will state /docs/xp/7.0 when 7.1 is released. A fix release should never change the version of the doc, or even require a new doc release IMHO

**Comment by jsi** [comment]
Okay.  Then we need two variables, one for full version number that can be used to create links to latest doc and downloads, and one for just feature-version number.  Since the existing variable stated version 7.0.0 (including bugfix number), I thought it was okay to use it, but I can fix this quickly.

**Comment by jsi** [comment]
Better now?

**Comment by sigdestad** [comment]
Hmm maybe I'm wrong. Lets talk about it
