### ISSUE TITLE
Cleanup TODOs: Document Standard Properties in CMS

### ISSUE THREAD

**Issue by jsi** [enonic/doc-xp#73]
https://developer.enonic.com/docs/xp/stable/cms#standard_properties

**Comment by hjelmevold** [comment]
Do we have anything about this in the XP6 documentation? I can only find this page: https://xp.readthedocs.io/en/stable/developer/site/content-types/content-anatomy.html
…but those properties are already documented in cms.adoc, under the heading "Content indexing". So if this is already documented, perhaps we only need to remove the heading "Standard properties"?

**Comment by poi33** [comment]
Closing this since the standard_properties from the old docs are moved over.
