### ISSUE TITLE
Create issues for all TODOs spread over the docs

### ISSUE THREAD

**Issue by alansemenov** [enonic/doc-xp#91]
We need to create a separate issue for every page with "TODO", and remove TODOs from the page and eventually from the entire portal. Every issue should have a link to the page and describe which parts of the page require work (if the page is not totally empty).

**Example 1** (an empty page with nothing but "TODO" on it):
https://developer.enonic.com/docs/xp/stable/runtime/media/image-service

Create an issue titled "TODO: Image Service" with link to the page in the issue body

**Example 2** (page with content, with some TODOs in various places):
https://developer.enonic.com/docs/xp/stable/deployment/config

Create an issues titled "TODO: Deployment / configuration". In the issue body have a link to the page, and then describe the list of TODOs:

_* "Variables" section: how to inject variables
* "Application config" section: Link to details on how to use configuration files in apps.
...and so on_

**Comment by alansemenov** [comment]
@hjelmevold Remember to remove the actual "TODOs" from the docs: https://developer.enonic.com/search?q=todo (also good idea that we actually covered all of them with the issues)

**Comment by hjelmevold** [comment]
I've now commented out all TODOs so they are no longer visible on the site
(see commit https://github.com/enonic/doc-xp/commit/888057786ef074d503c7eb16b5e045b6c360ef96)
